version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=listings_db
    networks:
      - app-network

  express-api:
    build:
      context: .
      dockerfile: Dockerfile_express
    container_name: express-api
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - DATABASE_NAME=listings_db
      - PORT=3000
    volumes:
      - ./account-key.json:/app/account-key.json
      - ./logs:/app/logs
    networks:
      - app-network
    restart: unless-stopped

  trestle-crawler:
    build:
      context: .
      dockerfile: Dockerfile_crawler
    container_name: trestle-crawler
    depends_on:
      - mongodb
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - DATABASE_NAME=listings_db
    volumes:
      - ./account-key.json:/app/account-key.json
      - ./logs:/app/logs
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
